export const GET_APPOINTMENTS_LIST = "GET_APPOINTMENTS_LIST"
export const GET_STUDENTS_LIST = "GET_STUDENTS_LIST"

// types for auth
export const REGISTER_SUCCESSFUL = "REGISTER_SUCCESSFUL"
export const REGISTER_FAILED = "REGISTER_FAILED"
export const GET_USER = "GET_USER"
export const LOGIN_SUCCESSFUL = "LOGIN_SUCCESSFUL"
export const LOGIN_FAILED = "LOGIN_FAILED"
export const LOGOUT = "LOGOUT"
export const SET_NAVBAR_LIST = "SET_NAVBAR_LIST"

